### ISSUE TITLE
Correct way to install library in IOS

### ISSUE THREAD

**Issue by kyesw** [Johan-dutoit/react-native-movesense#3]
Hello,

I am trying to install this library in my expo project in IOS.

I have done "yarn add react-native-movesense"

Without adding "pod 'Movesense', :git => 'ssh://git@altssh.bitbucket.org:443/suunto/movesense-mobile-lib.git'" line to the "Podfile", "cd ios && pod install" failed.

When I do "pod install"after adding  "pod 'Movesense', :git => 'ssh://git@altssh.bitbucket.org:443/suunto/movesense-mobile-lib.git'" line to the "Podfile", it gives me an error "Please make sure you have the correct access rights and the repository exists."

Can you provide more detailed explanation on how to instal pod?

Thank you in advance.

**Comment by Johan-dutoit** [comment]
Unfortunately this library doesn't support expo, or technically, expo doesn't support this library.

You'll have to eject and then follow the standard installation steps.

**Comment by kyesw** [comment]
Thank you for the explanation.
The problem was with the bitbucket public key setting.
